[build]
  functions = "netlify/functions"
  
[functions]
  # Define la carpeta donde están tus funciones
  directory = "netlify/functions"

[context.production.environment]
  # Define variables de entorno para el entorno de producción
  RECAPTCHA_SECRET_KEY = "your-recaptcha-secret-key"
  EMAILJS_SERVICE_ID = "your-emailjs-service-id"
  EMAILJS_TEMPLATE_ID = "your-emailjs-template-id"
  EMAILJS_API_KEY = "your-emailjs-api-key"

[context.deploy-preview.environment]
  # Define variables de entorno para el entorno de vista previa
  RECAPTCHA_SECRET_KEY = "your-recaptcha-secret-key"
  EMAILJS_SERVICE_ID = "your-emailjs-service-id"
  EMAILJS_TEMPLATE_ID = "your-emailjs-template-id"
  EMAILJS_API_KEY = "your-emailjs-api-key"